name: Update Commit Count

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_commit_count:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Fetch commit count and update file
      run: node update_commit_count.js

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add commit_count.json
        git commit -m "Update commit count"
        git push